namespace WTDeck.Core.KeyBindings;

public static class ScanCodeMap
{
    private static readonly Dictionary<int, string> Names = new()
    {
        [1] = "Esc",
        [2] = "1",
        [3] = "2",
        [4] = "3",
        [5] = "4",
        [6] = "5",
        [7] = "6",
        [8] = "7",
        [9] = "8",
        [10] = "9",
        [11] = "0",
        [14] = "Backspace",
        [15] = "Tab",
        [16] = "Q",
        [17] = "W",
        [18] = "E",
        [19] = "R",
        [20] = "T",
        [21] = "Y",
        [22] = "U",
        [23] = "I",
        [24] = "O",
        [25] = "P",
        [28] = "Enter",
        [29] = "LCtrl",
        [30] = "A",
        [31] = "S",
        [32] = "D",
        [33] = "F",
        [34] = "G",
        [35] = "H",
        [36] = "J",
        [37] = "K",
        [38] = "L",
        [42] = "LShift",
        [44] = "Z",
        [45] = "X",
        [46] = "C",
        [47] = "V",
        [48] = "B",
        [49] = "N",
        [50] = "M",
        [54] = "RShift",
        [56] = "LAlt",
        [57] = "Space",
        [58] = "CapsLock",
        [59] = "F1",
        [60] = "F2",
        [61] = "F3",
        [62] = "F4",
        [63] = "F5",
        [64] = "F6",
        [65] = "F7",
        [66] = "F8",
        [67] = "F9",
        [68] = "F10",
        [87] = "F11",
        [88] = "F12",
        [200] = "Up",
        [203] = "Left",
        [205] = "Right",
        [208] = "Down",
        [209] = "PageDown",
        [210] = "Insert",
        [211] = "Delete",
        [199] = "Home",
        [207] = "End",
        [201] = "PageUp",
    };

    public static string GetName(int scanCode) =>
        Names.GetValueOrDefault(scanCode, $"SC{scanCode}");
}
