<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\WTDeck.Core\WTDeck.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.2" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="..\WTDeck.Plugin\manifest.json" LogicalName="WTDeck.Plugin.manifest.json" />
    <EmbeddedResource Include="..\WTDeck.Plugin\plugin\index.html" LogicalName="WTDeck.Plugin.plugin.index.html" />
    <EmbeddedResource Include="..\WTDeck.Plugin\plugin\index.js" LogicalName="WTDeck.Plugin.plugin.index.js" />
    <EmbeddedResource Include="..\WTDeck.Plugin\plugin\property-inspector.html" LogicalName="WTDeck.Plugin.plugin.property-inspector.html" />
    <EmbeddedResource Include="..\WTDeck.Plugin\assets\gear-retracted.svg" LogicalName="WTDeck.Plugin.assets.gear-retracted.svg" />
    <EmbeddedResource Include="..\WTDeck.Plugin\assets\gear-deployed.svg" LogicalName="WTDeck.Plugin.assets.gear-deployed.svg" />
    <EmbeddedResource Include="..\WTDeck.Plugin\assets\gear-deploying.svg" LogicalName="WTDeck.Plugin.assets.gear-deploying.svg" />
    <EmbeddedResource Include="..\WTDeck.Plugin\assets\gear-retracting.svg" LogicalName="WTDeck.Plugin.assets.gear-retracting.svg" />
    <EmbeddedResource Include="..\WTDeck.Plugin\assets\gear-damaged.svg" LogicalName="WTDeck.Plugin.assets.gear-damaged.svg" />
    <EmbeddedResource Include="..\WTDeck.Plugin\assets\gear-disabled.svg" LogicalName="WTDeck.Plugin.assets.gear-disabled.svg" />
    <EmbeddedResource Include="..\WTDeck.Plugin\assets\gear-unknown.svg" LogicalName="WTDeck.Plugin.assets.gear-unknown.svg" />
    <EmbeddedResource Include="..\WTDeck.Plugin\assets\gear-blink-off.svg" LogicalName="WTDeck.Plugin.assets.gear-blink-off.svg" />
    <EmbeddedResource Include="..\WTDeck.Plugin\assets\flare-ready.svg" LogicalName="WTDeck.Plugin.assets.flare-ready.svg" />
    <EmbeddedResource Include="..\WTDeck.Plugin\assets\flare-unavailable.svg" LogicalName="WTDeck.Plugin.assets.flare-unavailable.svg" />
    <EmbeddedResource Include="..\WTDeck.Plugin\assets\flare-unknown.svg" LogicalName="WTDeck.Plugin.assets.flare-unknown.svg" />
    <EmbeddedResource Include="..\WTDeck.Plugin\assets\flight-alerts-panel.svg" LogicalName="WTDeck.Plugin.assets.flight-alerts-panel.svg" />
    <EmbeddedResource Include="..\WTDeck.Plugin\assets\plugin-icon.svg" LogicalName="WTDeck.Plugin.assets.plugin-icon.svg" />
    <EmbeddedResource Include="..\WTDeck.Plugin\assets\category-icon.svg" LogicalName="WTDeck.Plugin.assets.category-icon.svg" />
  </ItemGroup>
</Project>
